shoppingproject/cart/urls.py
from django.urls import path
from .import views


app_name='cart'


urlpatterns=[
       path('add/<int:product_id>/',views.add_cart,name='add_cart'),
       path('',views.cart_detail, name='cart_detail'),
       path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
       path('full_remove/<int:product_id>/',views.full_remove,name='full_remove'),
]

shoppingproject/search_app/urls.py
from django.urls import path
from .import views

app_name='search_app'
urlpatterns=[
       path('',views.SearchResult, name='SearchResult'),
]

shoppingproject/shopapp/urls.py
from django.urls import path
from .import views
app_name='shopapp'

urlpatterns = [
    path('',views.allprodcat,name='allprodcat'),
    path('<slug:c_slug>/',views.allprodcat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.proDetail, name='prodCatdetail'),
]

shoppingproject/shoppingproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

from shoppingproject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shopapp/', include("shopapp.urls")),
    path('search/',include('search_app.urls')),
    path('cart/',include('cart.urls')),

]
if settings.DEBUG:
   urlpatterns += static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)
   urlpatterns += static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

shoppingproject/cart/models.py
from django.db import models
from shopapp.models import Product

# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)

    class Meta:
        db_table='Cart'
        ordering=['date_added']
    def __str__(self):
        return '{}'.format(self.cart_id)


class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=TypeError)
    class Meta:

        db_table='CartItem'

    def  sub_total(self):
        return self.product.price * self.quantity
    def  __str__(self):
        return '{}'.format(self.product)

shoppingproject/search_app/models.py
from django.db import models

# Create your models here.

shoppingproject/shopapp/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'
    def get_url(self):
        return reverse('shopapp:products_by_category',args=[self.slug])

    def __str__(self):
        return   '{}'.format(self.name)

class Product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product', blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)




    def  get_url(self):
        return reverse('shopapp:prodCatdetail',args=[self.category.slug,self.slug])
    class Meta:
        ordering=('name',)
        verbose_name='product'
        verbose_name_plural='products'

    def __str__(self):
         return  '{}'.format(self.name)

shoppingproject/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shopapp.models import Product
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.


def cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart

def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
         cart=Cart.objects.get(cart_id=cart_id(request))
    except Cart.DoesNotExist:
          cart=Cart.objects.create(
                 cart_id=cart_id(request)
          )
          cart.save()
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
           cart_item.quantity +=1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')
def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity

    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,Total=total,counter=counter))


def cart_remove(request,product_id):
    cart=Cart.Objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity >1:
        cart_item.quantity -=1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_details')
def full_remove(request,product_id):
    cart = Cart.Objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

shoppingproject/search_app/views.py
from django.shortcuts import render
from shopapp.models import Product
from django.db.models import Q

def SearchResult(request):
    products=None
    query=None
    if'q' in request.GET:
        query= request.GET.get('q')
        products=Product.objects.all().filter(Q(name__contains=query)  |  Q(description__contains=query))
        return render(request,'search.html',{'query':query,'products':products})

shoppingproject/shopapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse

from .models import Category,Product
from django.core.paginator import  Paginator,EmptyPage,InvalidPage

# Create your views here.
#

def allprodcat(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug!=None:
        c_page=get_object_or_404(Category,slug=c_slug)
        products_list=Product.objects.all().filter(category=c_page,available=True)
    else:
        products_list=Product.objects.all().filter(available=True)
    paginator=Paginator(products_list,6)
    try:
        page=int(request.GET.get('page',1))
    except :
        page=1
    try:
        products=paginator.page(page)
    except(EmptyPage,InvalidPage):
        products=paginator,page(paginator.num_pages)



    return render(request,"category.html",{'category':c_page,'products':products})

def proDetail(request,c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})

shoppingproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
     <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %} </title>

</head>
<body>
<div>
    <div class="container"></div>
{% include 'header.html' %}
{% include 'nav.html' %}
{%  block content %}
{%  endblock %}

</div>
{% include 'footer.html' %}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

shoppingproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

          {{product.description|truncatewords:155 }}



{% endblock %}
{% block title %}
{% if category %}
          {{product.name}}- ABCD super market

      {% endif %}
{% endblock %}

{% block  content %}
<div class="row my_prod_row_class">
    <div class="mx_auto">
         <p> <a href="{% url 'shopapp:allprodcat' %}">Home</a> | <a href="{{product.category.get_url}}">{{product.category}}</a>|{{product.name}}</p>
    </div>
<div class="container">
<br>
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem">
            <img src="{{product.image.url}}" height="300px;" width="300px;" alt="{{product.name}}">


        </div>
    </div>
    <div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <h1 class="my_prod_title">{{product.name}}</h1>
            <p>{{product.price}}</p>
             <p class="my_title" >product Description</p>
             <p class="text-justify my_prod-text">{{product.description}}</p>
            {% if product.stock <= 0 %}
            <p class="text-justify my-prod_text"><b>Out of stock</b></p>
            {% else %}
            <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add to  Cart</a>
            {% endif %}


        </div>

    </div>
</div></div>
{% endblock %}

shoppingproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
      {% if category %}
          {{category.description|truncatewords:155 }}
      {% else %}
           Welcome to ABCD  store   Here you can experience amazing shopping.....

      {% endif %}
{% endblock %}
{% block title %}
{% if category %}
          {{category.name}}- ABCD super market
      {% else %}
         See our new collection -ABCD  SUPER MARKET

      {% endif %}
{% endblock %}
{% block content %}
{% if category %}
      <div>
          <div class="row my_row_class">
              <div class="mx-auto"></div>
              <p style="text-align:left;"><a href="{% url 'shopapp:allprodcat' %}">our product Collections </a></p>
          </div>
      </div>
      {% endif %}
<div class="mx_auto">
   {% if category %}
    <img class="my_image" src="{{ category.image.url }}" height="500px" width="1995px"  alt="{{category.name}}">
</div>
    <br>
<div>
    <h1 class="text-center my_title">{{category.name}}</h1>
    <h1 class="text-justify">{{category.description}}</h1>
</div>
    {% else %}
<div>
<img  class="my_image my_image_padding" src="{% static 'img/banner.png' %}" height="720px;"   alt="our products" >
</div>
<br>
<div>
    <h1 class="text-center my_title"> Our collections </h1>
    <p class="text-justify">The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.</p>

</div>
 {% endif %}
<div class="container">
    <div class="row mx_auto">
        {%  for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 xol-lg-4">
            <div class="card text-center" style="min-width:18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{ product.image.url }}" height="200px" width="100px"  alt="{{product.name}}"></a>
                <div class="card-body">
                   <h4> {{ product.name }}</h4>
                      <p> {{ product.price }}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx_auto">
         {% if products.paginator.num_pages > 1 %}
        <hr>
        <div class="text-center">
            {% for pg in  products.paginator.page_range %}
                  <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}"> {{pg}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    <br>

</div>
{% endblock %}

shoppingproject/templates/footer.html
<div class="footer navbar-fixed-bottom my-footer">
    <p class="text-center">@copy;ABCD tech pvt ltd. All rights Reserved</p>
</div>

shoppingproject/templates/header.html
{% load static %}
<header>
     <center>
       <a href ="{% url 'shopapp:allprodcat' %}"></a><img src="{% static 'img/logo.png' %}"alt="logimage" width="250px;" height="250px;">

  </center>
</header>

shoppingproject/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item">
        <a class="nav-link" href="#">Home</a>
      </li>
      <li class="nav-item dropdown {% if 'shopapp' in request.path %} active {% endif %}">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Shop
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'shopapp:allprodcat' %}">All products</a>
             {% for cat in links %}
          <a class="dropdown-item" href="{{ cat.get_url}}">{{cat.name}}</a>
            {% endfor %}

        </div>
      </li>
      {% if item_count > 0 %}
      <li class="nav-item">
        <a class="nav-link disabled" href="{% url 'cart:cart_detail' %}"><i class="fa fa-shopping-cart"></i>{{item_count}}</a>
      </li>
      {% endif %}
    </ul>
    <form class="d_flex" action="{% url 'search_app:SearchResult' %}" method="get">
      {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Search" name="q" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fa fa-search"></i></button>
    </form>
  </div>
</nav>

shoppingproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

          {{product.description|truncatewords:155 }}



{% endblock %}
{% block title %}
{% if category %}
          {{product.name}}- ABCD super market

      {% endif %}
{% endblock %}

{% block  content %}
<div class="row my_prod_row_class">
    <div class="mx_auto">
         <p> <a href="{% url 'shopapp:allprodcat' %}">Home</a> | <a href="{{product.category.get_url}}">{{product.category}}</a>|{{product.name}}</p>
    </div>
<div class="container">
<br>
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem">
            <img src="{{product.image.url}}" height="300px;" width="300px;" alt="{{product.name}}">


        </div>
    </div>
    <div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <h1 class="my_prod_title">{{product.name}}</h1>
            <p>{{product.price}}</p>
             <p class="my_title" >product Description</p>
             <p class="text-justify my_prod-text">{{product.description}}</p>
            {% if product.stock <= 0 %}
            <p class="text-justify my-prod_text"><b>Out of stock</b></p>
            {% else %}
            <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add to  Cart</a>
            {% endif %}


        </div>

    </div>
</div>
{% endblock %}

shoppingproject/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

       We have  fresh vegetables and fruits.

{% endblock %}
{% block title %}
      search
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text">You have searched for:<bd>"{{query}}"</bd></p>
</div>
<div class="container">
    <div class="row mx_auto">
        {%  for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 xol-lg-4">
            <div class="card text-center" style="min-width:18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{ product.image.url }}" height="200px" width="200px"  alt="{{product.name}}"></a>
                <div class="card-body">
                   <h4> {{product.name}}</h4>
                      <p> {{product.price}}</p>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="row mx-auto">
            <p class="text-center my_search_text"> 0 results Found </p>
        </div>
        {% endfor %}
    </div>
{% endblock %}